version: '3.5'

services:
  brane-ide:
    image: epi-project/brane-ide
    ports:
      - "127.0.0.1:8888:8888"
    restart: always
    privileged: true
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      BRANE_MOUNT_DFS: redis

networks:
  default:
    external:
      name: kind
