version: '3'

services:
  scylla:
    image: scylladb/scylla:4.4.3
    ports:
      - "127.0.0.1:9042:9042"
    command: --smp 1
    restart: always

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: DOCKER://kafka:29092,HOST://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:29092,HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0

  registry:
    image: registry:2
    ports:
      # - "127.0.0.1:5000:5000"
      - "0.0.0.0:5000:5000"
    restart: always

  xenon:
    build:
      context: ./contrib/images
      dockerfile: Dockerfile.xenon
    ports:
      - "127.0.0.1:50051:50051"
    command: -v
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    restart: always

  #############
  ## JuiceFS ##
  #############

  minio:
    image: minio/minio
    ports:
      # - "127.0.0.1:9000:9000"
      - "0.0.0.0:9000:9000"
    command: server /data
    restart: always
    environment:
      MINIO_ROOT_USER: JntYwuVjKY5v5F2bPZr3aZtD
      MINIO_ROOT_PASSWORD: qBKuJxbCNa5bSCPQb3kEyB4s
    volumes:
      - data:/data

  redis:
    image: redis:6-alpine
    ports:
      # - "127.0.0.1:6379:6379"
      - "0.0.0.0:6379:6379"
    restart: always

  format:
    build:
      context: ./contrib/images
      dockerfile: Dockerfile.juicefs
    depends_on: 
      - minio
      - redis
    command: format --access-key JntYwuVjKY5v5F2bPZr3aZtD --secret-key qBKuJxbCNa5bSCPQb3kEyB4s --storage minio --bucket http://minio:9000/data redis brane

networks:
  default:
    external:
      name: brane

volumes:
  data:
